services:
  # Database for development
  mysql-dev:
    image: mysql:8.0
    container_name: start-from-scratch-mysql-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: start_from_scratch
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3307:3306" # Use port 3307 to avoid conflicts
    volumes:
      - mysql_dev_data:/var/lib/mysql
      - ./docker-from-scratch/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - app-network-dev
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_dev_data:
    driver: local

networks:
  app-network-dev:
    driver: bridge
